### ISSUE TITLE
Any chance for a fix for Sublime-Text 4?

### ISSUE THREAD

**Issue by jradxl** [edubart/nelua-sublime#1]
Doesn't seem to work for me on Sublime-Text3, and anyway Sublime3 always gives a dialogue to upgrade to Sublime-Text4 in the unregistered copy, which is not disableable.
So any chance of a upgrade to  Sublime-Text4
v3.2.2, build 3211

![image](https://user-images.githubusercontent.com/1639936/140528123-f0cf7fa2-3840-4588-a6e3-8d462f2858a4.png)

**Comment by ghost** [comment]
The plugin works fine on sublime text 4, you should update to sublime text 4.
